package cn.vpfinance.vpjr.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import cn.vpfinance.vpjr.greendao.Banner;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BANNER".
*/
public class BannerDao extends AbstractDao<Banner, Long> {

    public static final String TABLENAME = "BANNER";

    /**
     * Properties of entity Banner.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Bid = new Property(1, long.class, "bid", false, "BID");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Number = new Property(3, int.class, "number", false, "NUMBER");
        public final static Property Url = new Property(4, String.class, "url", false, "URL");
        public final static Property Imgurl = new Property(5, String.class, "imgurl", false, "IMGURL");
        public final static Property Picturename = new Property(6, String.class, "picturename", false, "PICTURENAME");
    };


    public BannerDao(DaoConfig config) {
        super(config);
    }
    
    public BannerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BANNER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BID\" INTEGER NOT NULL ," + // 1: bid
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"NUMBER\" INTEGER NOT NULL ," + // 3: number
                "\"URL\" TEXT," + // 4: url
                "\"IMGURL\" TEXT," + // 5: imgurl
                "\"PICTURENAME\" TEXT);"); // 6: picturename
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BANNER\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Banner entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getBid());
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getNumber());
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(5, url);
        }
 
        String imgurl = entity.getImgurl();
        if (imgurl != null) {
            stmt.bindString(6, imgurl);
        }
 
        String picturename = entity.getPicturename();
        if (picturename != null) {
            stmt.bindString(7, picturename);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Banner readEntity(Cursor cursor, int offset) {
        Banner entity = new Banner( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // bid
            cursor.getInt(offset + 2), // type
            cursor.getInt(offset + 3), // number
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // url
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // imgurl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // picturename
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Banner entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBid(cursor.getLong(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setNumber(cursor.getInt(offset + 3));
        entity.setUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setImgurl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPicturename(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Banner entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Banner entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
