package cn.vpfinance.vpjr.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BORROWER_INFO".
 */
public class BorrowerInfo {

    private Long id;
    private long bid;
    private long pid;
    private String isCard;
    private long age;
    private double money;
    private String realName;
    private double credit;
    private String remark;

    public BorrowerInfo() {
    }

    public BorrowerInfo(Long id) {
        this.id = id;
    }

    public BorrowerInfo(Long id, long bid, long pid, String isCard, long age, double money, String realName, double credit, String remark) {
        this.id = id;
        this.bid = bid;
        this.pid = pid;
        this.isCard = isCard;
        this.age = age;
        this.money = money;
        this.realName = realName;
        this.credit = credit;
        this.remark = remark;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getBid() {
        return bid;
    }

    public void setBid(long bid) {
        this.bid = bid;
    }

    public long getPid() {
        return pid;
    }

    public void setPid(long pid) {
        this.pid = pid;
    }

    public String getIsCard() {
        return isCard;
    }

    public void setIsCard(String isCard) {
        this.isCard = isCard;
    }

    public long getAge() {
        return age;
    }

    public void setAge(long age) {
        this.age = age;
    }

    public double getMoney() {
        return money;
    }

    public void setMoney(double money) {
        this.money = money;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public double getCredit() {
        return credit;
    }

    public void setCredit(double credit) {
        this.credit = credit;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
