package cn.vpfinance.vpjr.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "INVEST_RECORD".
 */
public class InvestRecord {

    private Long id;
    private long page;
    private long pageSize;
    private long totalPage;
    private long iid;
    private int loanType;
    private int isSucceed;
    private int product;
    private double tenderMoney;
    private String tenderTime;
    private long voucherId;
    private double voucherMoney;

    public InvestRecord() {
    }

    public InvestRecord(Long id) {
        this.id = id;
    }

    public InvestRecord(Long id, long page, long pageSize, long totalPage, long iid, int loanType, int isSucceed, int product, double tenderMoney, String tenderTime, long voucherId, double voucherMoney) {
        this.id = id;
        this.page = page;
        this.pageSize = pageSize;
        this.totalPage = totalPage;
        this.iid = iid;
        this.loanType = loanType;
        this.isSucceed = isSucceed;
        this.product = product;
        this.tenderMoney = tenderMoney;
        this.tenderTime = tenderTime;
        this.voucherId = voucherId;
        this.voucherMoney = voucherMoney;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPage() {
        return page;
    }

    public void setPage(long page) {
        this.page = page;
    }

    public long getPageSize() {
        return pageSize;
    }

    public void setPageSize(long pageSize) {
        this.pageSize = pageSize;
    }

    public long getTotalPage() {
        return totalPage;
    }

    public void setTotalPage(long totalPage) {
        this.totalPage = totalPage;
    }

    public long getIid() {
        return iid;
    }

    public void setIid(long iid) {
        this.iid = iid;
    }

    public int getLoanType() {
        return loanType;
    }

    public void setLoanType(int loanType) {
        this.loanType = loanType;
    }

    public int getIsSucceed() {
        return isSucceed;
    }

    public void setIsSucceed(int isSucceed) {
        this.isSucceed = isSucceed;
    }

    public int getProduct() {
        return product;
    }

    public void setProduct(int product) {
        this.product = product;
    }

    public double getTenderMoney() {
        return tenderMoney;
    }

    public void setTenderMoney(double tenderMoney) {
        this.tenderMoney = tenderMoney;
    }

    public String getTenderTime() {
        return tenderTime;
    }

    public void setTenderTime(String tenderTime) {
        this.tenderTime = tenderTime;
    }

    public long getVoucherId() {
        return voucherId;
    }

    public void setVoucherId(long voucherId) {
        this.voucherId = voucherId;
    }

    public double getVoucherMoney() {
        return voucherMoney;
    }

    public void setVoucherMoney(double voucherMoney) {
        this.voucherMoney = voucherMoney;
    }

}
