package cn.vpfinance.vpjr.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MY_INVEST_RECORD".
 */
public class MyInvestRecord {

    private Long id;
    private long page;
    private long pageSize;
    private long totalPage;
    private long iid;
    private String borrowername;
    private String deadline;
    private double interestRate;
    private double issueLoan;
    private String loanTitle;
    private double money;
    private String refundWay;
    private double schedule;
    private double tenderMoney;
    private String tenderTime;

    public MyInvestRecord() {
    }

    public MyInvestRecord(Long id) {
        this.id = id;
    }

    public MyInvestRecord(Long id, long page, long pageSize, long totalPage, long iid, String borrowername, String deadline, double interestRate, double issueLoan, String loanTitle, double money, String refundWay, double schedule, double tenderMoney, String tenderTime) {
        this.id = id;
        this.page = page;
        this.pageSize = pageSize;
        this.totalPage = totalPage;
        this.iid = iid;
        this.borrowername = borrowername;
        this.deadline = deadline;
        this.interestRate = interestRate;
        this.issueLoan = issueLoan;
        this.loanTitle = loanTitle;
        this.money = money;
        this.refundWay = refundWay;
        this.schedule = schedule;
        this.tenderMoney = tenderMoney;
        this.tenderTime = tenderTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPage() {
        return page;
    }

    public void setPage(long page) {
        this.page = page;
    }

    public long getPageSize() {
        return pageSize;
    }

    public void setPageSize(long pageSize) {
        this.pageSize = pageSize;
    }

    public long getTotalPage() {
        return totalPage;
    }

    public void setTotalPage(long totalPage) {
        this.totalPage = totalPage;
    }

    public long getIid() {
        return iid;
    }

    public void setIid(long iid) {
        this.iid = iid;
    }

    public String getBorrowername() {
        return borrowername;
    }

    public void setBorrowername(String borrowername) {
        this.borrowername = borrowername;
    }

    public String getDeadline() {
        return deadline;
    }

    public void setDeadline(String deadline) {
        this.deadline = deadline;
    }

    public double getInterestRate() {
        return interestRate;
    }

    public void setInterestRate(double interestRate) {
        this.interestRate = interestRate;
    }

    public double getIssueLoan() {
        return issueLoan;
    }

    public void setIssueLoan(double issueLoan) {
        this.issueLoan = issueLoan;
    }

    public String getLoanTitle() {
        return loanTitle;
    }

    public void setLoanTitle(String loanTitle) {
        this.loanTitle = loanTitle;
    }

    public double getMoney() {
        return money;
    }

    public void setMoney(double money) {
        this.money = money;
    }

    public String getRefundWay() {
        return refundWay;
    }

    public void setRefundWay(String refundWay) {
        this.refundWay = refundWay;
    }

    public double getSchedule() {
        return schedule;
    }

    public void setSchedule(double schedule) {
        this.schedule = schedule;
    }

    public double getTenderMoney() {
        return tenderMoney;
    }

    public void setTenderMoney(double tenderMoney) {
        this.tenderMoney = tenderMoney;
    }

    public String getTenderTime() {
        return tenderTime;
    }

    public void setTenderTime(String tenderTime) {
        this.tenderTime = tenderTime;
    }

}
