package cn.vpfinance.vpjr.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private Long userId;
    /** Not-null value. */
    private String userName;
    private String realName;
    private String sessionId;
    private String cellPhone;
    private String email;
    private String emailPass;
    private String userpass;
    private String head;
    private String identityCard;
    private Double cashBalance;
    private Double netAsset;
    private Double frozenAmtN;
    private Double paying;
    private Double dBid;
    private Double dSum;
    private Double invest;
    private Double preIncome;
    private Boolean hasTradePassword;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Long userId, String userName, String realName, String sessionId, String cellPhone, String email, String emailPass, String userpass, String head, String identityCard, Double cashBalance, Double netAsset, Double frozenAmtN, Double paying, Double dBid, Double dSum, Double invest, Double preIncome, Boolean hasTradePassword) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.realName = realName;
        this.sessionId = sessionId;
        this.cellPhone = cellPhone;
        this.email = email;
        this.emailPass = emailPass;
        this.userpass = userpass;
        this.head = head;
        this.identityCard = identityCard;
        this.cashBalance = cashBalance;
        this.netAsset = netAsset;
        this.frozenAmtN = frozenAmtN;
        this.paying = paying;
        this.dBid = dBid;
        this.dSum = dSum;
        this.invest = invest;
        this.preIncome = preIncome;
        this.hasTradePassword = hasTradePassword;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getCellPhone() {
        return cellPhone;
    }

    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmailPass() {
        return emailPass;
    }

    public void setEmailPass(String emailPass) {
        this.emailPass = emailPass;
    }

    public String getUserpass() {
        return userpass;
    }

    public void setUserpass(String userpass) {
        this.userpass = userpass;
    }

    public String getHead() {
        return head;
    }

    public void setHead(String head) {
        this.head = head;
    }

    public String getIdentityCard() {
        return identityCard;
    }

    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard;
    }

    public Double getCashBalance() {
        return cashBalance;
    }

    public void setCashBalance(Double cashBalance) {
        this.cashBalance = cashBalance;
    }

    public Double getNetAsset() {
        return netAsset;
    }

    public void setNetAsset(Double netAsset) {
        this.netAsset = netAsset;
    }

    public Double getFrozenAmtN() {
        return frozenAmtN;
    }

    public void setFrozenAmtN(Double frozenAmtN) {
        this.frozenAmtN = frozenAmtN;
    }

    public Double getPaying() {
        return paying;
    }

    public void setPaying(Double paying) {
        this.paying = paying;
    }

    public Double getDBid() {
        return dBid;
    }

    public void setDBid(Double dBid) {
        this.dBid = dBid;
    }

    public Double getDSum() {
        return dSum;
    }

    public void setDSum(Double dSum) {
        this.dSum = dSum;
    }

    public Double getInvest() {
        return invest;
    }

    public void setInvest(Double invest) {
        this.invest = invest;
    }

    public Double getPreIncome() {
        return preIncome;
    }

    public void setPreIncome(Double preIncome) {
        this.preIncome = preIncome;
    }

    public Boolean getHasTradePassword() {
        return hasTradePassword;
    }

    public void setHasTradePassword(Boolean hasTradePassword) {
        this.hasTradePassword = hasTradePassword;
    }

}
