package cn.vpfinance.vpjr.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BANK_CARD".
 */
public class BankCard {

    private Long id;
    private long page;
    private long pageSize;
    private long totalPage;
    private long bid;
    /** Not-null value. */
    private String accountName;
    /** Not-null value. */
    private String bankAccount;
    /** Not-null value. */
    private String bankname;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String branch;
    /** Not-null value. */
    private String province;
    /** Not-null value. */
    private String city;

    public BankCard() {
    }

    public BankCard(Long id) {
        this.id = id;
    }

    public BankCard(Long id, long page, long pageSize, long totalPage, long bid, String accountName, String bankAccount, String bankname, String name, String branch, String province, String city) {
        this.id = id;
        this.page = page;
        this.pageSize = pageSize;
        this.totalPage = totalPage;
        this.bid = bid;
        this.accountName = accountName;
        this.bankAccount = bankAccount;
        this.bankname = bankname;
        this.name = name;
        this.branch = branch;
        this.province = province;
        this.city = city;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPage() {
        return page;
    }

    public void setPage(long page) {
        this.page = page;
    }

    public long getPageSize() {
        return pageSize;
    }

    public void setPageSize(long pageSize) {
        this.pageSize = pageSize;
    }

    public long getTotalPage() {
        return totalPage;
    }

    public void setTotalPage(long totalPage) {
        this.totalPage = totalPage;
    }

    public long getBid() {
        return bid;
    }

    public void setBid(long bid) {
        this.bid = bid;
    }

    /** Not-null value. */
    public String getAccountName() {
        return accountName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /** Not-null value. */
    public String getBankAccount() {
        return bankAccount;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /** Not-null value. */
    public String getBankname() {
        return bankname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getBranch() {
        return branch;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBranch(String branch) {
        this.branch = branch;
    }

    /** Not-null value. */
    public String getProvince() {
        return province;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProvince(String province) {
        this.province = province;
    }

    /** Not-null value. */
    public String getCity() {
        return city;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCity(String city) {
        this.city = city;
    }

}
