package cn.vpfinance.vpjr.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BANNER".
 */
public class Banner {

    private Long id;
    private long bid;
    private int type;
    private int number;
    private String url;
    private String imgurl;
    private String picturename;

    public Banner() {
    }

    public Banner(Long id) {
        this.id = id;
    }

    public Banner(Long id, long bid, int type, int number, String url, String imgurl, String picturename) {
        this.id = id;
        this.bid = bid;
        this.type = type;
        this.number = number;
        this.url = url;
        this.imgurl = imgurl;
        this.picturename = picturename;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getBid() {
        return bid;
    }

    public void setBid(long bid) {
        this.bid = bid;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getImgurl() {
        return imgurl;
    }

    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    public String getPicturename() {
        return picturename;
    }

    public void setPicturename(String picturename) {
        this.picturename = picturename;
    }

}
