package cn.vpfinance.vpjr.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUERY_PAGE".
 */
public class QueryPage {

    private Long id;
    private long page;
    private long pageSize;
    private long totalPage;
    /** Not-null value. */
    private String qid;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String time;
    private double money;
    /** Not-null value. */
    private String moneyDetail;
    /** Not-null value. */
    private String progress;
    /** Not-null value. */
    private String eid;

    public QueryPage() {
    }

    public QueryPage(Long id) {
        this.id = id;
    }

    public QueryPage(Long id, long page, long pageSize, long totalPage, String qid, String type, String time, double money, String moneyDetail, String progress, String eid) {
        this.id = id;
        this.page = page;
        this.pageSize = pageSize;
        this.totalPage = totalPage;
        this.qid = qid;
        this.type = type;
        this.time = time;
        this.money = money;
        this.moneyDetail = moneyDetail;
        this.progress = progress;
        this.eid = eid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getPage() {
        return page;
    }

    public void setPage(long page) {
        this.page = page;
    }

    public long getPageSize() {
        return pageSize;
    }

    public void setPageSize(long pageSize) {
        this.pageSize = pageSize;
    }

    public long getTotalPage() {
        return totalPage;
    }

    public void setTotalPage(long totalPage) {
        this.totalPage = totalPage;
    }

    /** Not-null value. */
    public String getQid() {
        return qid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQid(String qid) {
        this.qid = qid;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    public double getMoney() {
        return money;
    }

    public void setMoney(double money) {
        this.money = money;
    }

    /** Not-null value. */
    public String getMoneyDetail() {
        return moneyDetail;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMoneyDetail(String moneyDetail) {
        this.moneyDetail = moneyDetail;
    }

    /** Not-null value. */
    public String getProgress() {
        return progress;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProgress(String progress) {
        this.progress = progress;
    }

    /** Not-null value. */
    public String getEid() {
        return eid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEid(String eid) {
        this.eid = eid;
    }

}
